### PR TITLE
allow generating module_generator path for any path

### PR DESCRIPTION
**Pull request by Wurstnase**
https://github.com/ThrowTheSwitch/Ceedling/issues/208

inc_root is already working. But not source_root and any path which are already defined in module_generator.yml

### CODE REVIEW

**Comment by Wurstnase** [comment]
Unfortunately I've got an error when the file exists:

```
rake aborted!
ERROR: File temp already exists. Exiting.
myproject/vendor/ceedling/vendor/unity/auto/generate_module.rb:197:in `generate'
myproject/vendor/ceedling/plugins/module_generator/lib/module_generator.rb:17:in `create'
vendor/ceedling/plugins/module_generator/module_generator.rake:20:in `block (3 levels) in <top (required)>'
vendor/ceedling/plugins/module_generator/module_generator.rake:13:in `each'
vendor/ceedling/plugins/module_generator/module_generator.rake:13:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/ceedling-0.28.2/bin/ceedling:287:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/ceedling-0.28.2/bin/ceedling:274:in `<top (required)>'
/usr/local/bin/ceedling:22:in `load'
/usr/local/bin/ceedling:22:in `<main>'
Tasks: TOP => module:create
(See full trace by running task with --trace)
ERROR: Ceedling Failed
Exception raised in plugin: stdout_pretty_tests_report, in method post_error
myproject/vendor/ceedling/lib/ceedling/plugin_manager.rb:100:in `block in execute_plugins': undefined method `post_error' for #<StdoutPrettyTestsReport:0x0055a7daa44a98> (NoMethodError)
Did you mean?  post_test
        from myproject/vendor/ceedling/lib/ceedling/plugin_manager.rb:98:in `each'
        from myproject/vendor/ceedling/lib/ceedling/plugin_manager.rb:98:in `execute_plugins'
        from myproject/vendor/ceedling/lib/ceedling/plugin_manager.rb:87:in `post_error'
        from vendor/ceedling/lib/../lib/ceedling/rakefile.rb:84:in `block in <top (required)>'
```

**Comment by Tyrn** [comment]
For those still wondering about the proper workaround: follow #208, then change `vendor/ceedling/plugins/module_generator/config/module_generator.yml`, like this (for instance):
```
:module_generator:
  :project_root: ./
  :source_root:  Src/
  :inc_root:     Inc/
  :test_root:    test/
```
I'd be grateful for a better solution.

**Comment by mvandervoord** [comment]
Does anyone know if this is still an issue?

**Comment by Tyrn** [comment]
Do I still have to follow this routine?

myproject $ cd ..
$ ceedling new myproject
$ cd myproject/vendor/
$ rm -rf ceedling/
$ git clone --recursive https://github.com/throwtheswitch/ceedling.git

or update via gem should suffice?
I'm ready to make a clean experiment; suggest your guidelines.

**Comment by IrksomeZeus** [comment]
This works but I think it might be better to implement a fix where the module_generator.yml is merged into the project config (\vendor\ceedling\lib\ceedling\configurator.rb line 186)

As it is right now, the plugin configs are merged into the project configs with deep_merge! which overwrites any duplicate values in the project config with the values from the plugin config.

```ruby
    config_plugins.each do |plugin|
      config.deep_merge!( @yaml_wrapper.load(plugin) )
    end
```

I don't know Ruby very well and don't know if this would have a negative effect on other plugins but I think changing it to this would fix it using the non-dangerous deep_merge and switching the merge order:

```ruby
    config_plugins.each do |plugin|
      config = @yaml_wrapper.load(plugin).deep_merge(config)
    end
```

**Comment by dfridley** [comment]
FYI seems to work as intended if you comment out the lines in the

  vendor/ceedling/plugins/module_generator/config/module_generator.yml file 

or remove the file entirely.

Then can change the module generator paths in your project.yml file

**Comment by bdun** [comment]
Note, I had the same issue as this.  I just manually merged in the recommended fix and this fixed the generator, however it breaks the unit tests running.

I get this error:

~~~
unit_tests\_fff>ceedling test:encoder
Using fake function framework (fff)...


Test 'test_encoder.c'
---------------------
../../Project/motor_control/PWM.h:7:9: warning: #pragma once in main file
 #pragma once
         ^~~~
Generating runner for test_encoder.c...
Compiling test_encoder_runner.c...
Compiling test_encoder.c...
Compiling encoder.c...
Linking test_encoder.out...
Running test_encoder.out...
rake aborted!
NoMethodError: undefined method `plugins_display_raw_test_results' for #<Configurator:0x0000000003b7eb90>
C:/development/cframe/unit_tests/vendor/ceedling/lib/ceedling/plugin_manager.rb:75:in `post_test_fixture_execute'
C:/development/cframe/unit_tests/vendor/ceedling/lib/ceedling/generator.rb:172:in `generate_test_results'
C:/development/cframe/unit_tests/vendor/ceedling/lib/ceedling/rules_tests.rake:47:in `block in <top (required)>'
C:/development/cframe/unit_tests/vendor/ceedling/lib/ceedling/task_invoker.rb:74:in `invoke_test_results'
C:/development/cframe/unit_tests/vendor/ceedling/lib/ceedling/test_invoker.rb:104:in `block in setup_and_invoke'
C:/development/cframe/unit_tests/vendor/ceedling/lib/ceedling/test_invoker.rb:63:in `each'
C:/development/cframe/unit_tests/vendor/ceedling/lib/ceedling/test_invoker.rb:63:in `setup_and_invoke'
C:/development/cframe/unit_tests/vendor/ceedling/lib/ceedling/rules_tests.rake:62:in `block (2 levels) in <top (required)>'
C:/Ruby25-x64/bin/ceedling:23:in `load'
C:/Ruby25-x64/bin/ceedling:23:in `<main>'
Tasks: TOP => build/test/results/test_encoder.pass
(See full trace by running task with --trace)
~~~

Cheers.

**Pull request closed without merging**
