### PR TITLE
    Fixed #783 cmock of the wrong file is generated

### LINKED ISSUE #783: CMock of the wrong file is generated.
I have a problem with our project.  We have in different include subdirectories, headers with the same name.
eg.
```
foo/common/vm.h
foo/arm/vm.h
foo/arm64/vm.h
```
In tests, we want to cmock foo/common/vm.h ; I have ordered the includes (:path :sources) so that the -I option generated when compiling are in the right order (cf. #777 too).  But unfortunately, ceedling chooses the wrong header for cmock generation  (eg. generating the cmock_vm.h from foo/arm/vm.h instead of from foo/common/vm.h).

I'm in the process of debugging and patching the file collection methods, and would welcome any advice.

Related to #777

### PR DESCRIPTION
**Pull request by informatimago**
Do not add subdirectories of configured paths to the list of all headers,
    since the user may use ** himself, and may order the paths to include
    specific files.
    
    Added comment mentioning path of source file to generated files.

### CODE REVIEW

**Review by congyue-chewie — APPROVED** [review]
We noticed the same issue (wrong header being included, even though its path was not being included) on ceedling 0.32.
ceedling 0.31 does not have this issue, seems a regression.

**Comment by informatimago** [comment]
> We noticed the same issue (wrong header being included, even though its path was not being included, its parent path was) on ceedling 0.32.
> ceedling 0.31 does not have this issue, seems a regression.

Well, it was somewhat "random", before I fixed the order by sorting the results of Dir.glob.

**Comment by mkarlesky** [comment]
I am supposing this behavior has long since been resolved by other fixes? Directory listing results order is now enforced by explicit sorting, and a whole lot of patching and workarounds have been applied to overcome Rake::FileList shortcomings (FYI—to be entirely replaced in a future release).

**Comment by mkarlesky** [comment]
Since active maintenance of 0.31 is coming to an end with the impending release of a significant new version of Ceedling, I'm going to close this PR. I suspect this bug is fixed in the next major version. If not, it will be when we tackle a holistic approach to managing search paths and file finding. At present Ceedling is using some educated guesses in certain cases as it was built up from some simplistic assumptions and conventions that did not take into account edge cases like header files with the same name differentiated by directory paths.

If the problem persists in the coming Ceedling 1.0.0 (still known as 0.32 here and there), please open a new Github issues with details.

**Pull request closed without merging**
