### PR TITLE
gcov plugin - ReportGenerator

### PR DESCRIPTION
**Pull request by aschlicht**
These changes add ReportGenerator as an optional coverage report creation utility to the Ceedling gcov plugin. gcovr is still the default report creation utility. Both gcovr and / or ReportGenerator can be independently enabled or disabled. The ReportGenerator reports are output to a new subdirectory so both gcovr and ReportGenerator can be enabled without conflicting with each other.

The template project.yml files were also updated to use the new `:reports:` configuration item.
```
:gcov:
  :reports:
    - HtmlDetailed
```

### CODE REVIEW

**Comment by aschlicht** [comment]
One of three builds failed. It failed with the following error message.
```
The command "bundle install" failed and exited with 1 during .
```
Sounds like the build might pass if we re-run it. How do we re-run a build without pushing to the source branch?

**Comment by mvandervoord** [comment]
I'm afraid I've let this branch get stale. @aschlicht are you able to catch it up? I'll try to be better about going through this and approving it this time. Looking through it now, it looks great. :)

**Comment by aschlicht** [comment]
@mvandervoord Yes, I'll find some time soon to resolve the conflicts. I did notice that others made changes to the gcov plugin as well. Either they would have conflicts or I would, depending on which branch was merged in first.

**Comment by aschlicht** [comment]
@mvandervoord I merged the latest master into my fork and pushed the changed. There are no more merge conflicts; however, there are build errors. The errors relate to creating projects without documentation and upgrading projects. I didn't touch those features and have not yet dug into the error details, so I don't know why the checks failed.

**Comment by aschlicht** [comment]
@mvandervoord I resolved the checks failures by reverting the submodules to match the versions used in the ceedling master branch. I unintentionally committed and pushed the submodule updates. Please take another look and let me know if you want me to make any changes or feel free to complete the pull request. Thank you!

**Pull request merged**
