### PR TITLE
Generate deleteme file in test/support to make it easier to use ceedling out of the box with git

### PR DESCRIPTION
**Pull request by dpostorivo**
This attempts to alleviate some of the issues brought up in #182 by adding an empty file that can be added via git.

### CODE REVIEW

**Comment by kevlut** [comment]
I disagree with naming the file `deleteme`.  `deleteme` is misleading and provides no explanation to users why it exists.  I think a much more widely accepted and commonly known method is using a empty file named `.gitkeep`

**Comment by dpostorivo** [comment]
I don't mind changing it to that, but I want to reiterate the line of
thought that made me choose that name. When generating feeling out of the
box it will create this directory and a config that uses it, but it is not
needed if your set up does not need it. This is a quick fix to make it
easier for people first being introduced to Ceedling that don't understand
how to configure it for their exact set up.

The goal should then should be for the user to eventually 1. Remove the
support directory from the configuration and delete the tempfile keeping
the support directory around or 2. Utilize the support directory and delete
the tempfile because it's not needed.

Either way, the file is temporary and using gitkeep makes it sound more
permanent than it is supposed to be.

**Comment by mvandervoord** [comment]
I like the concept. I agree that `.gitkeep` might be a better name, even with your apt description.

It appears there is a conflict with this too... sorry about the delays that have caused that!

**Comment by dpostorivo** [comment]
@mvandervoord  updated and fixed conflict

**Pull request merged**
