### PR TITLE
Add support for mock generation to match the original headers Subdirectory

### PR DESCRIPTION
**Pull request by Hannes103**
My current project has a very nested folder structure which forces us to use globs in the `:include:` section of our `project.yml` which in turn at some point caused the gcc-compile command to exceed the maximum command-line length. 
In order to fix this i would like to eliminate the need for globs while also allowing us to mock headers located in Subdirectories. 

This pull request allows ceedling to generate mocks for headers located in sub directories. (also requested by #358 )

This allows headers in sub directories to be mocked without using globs in the `:include:` section of the `project.yml`
The following use-cases would now be supported:
```C
#include "Subdir/Mock_Test.h"
#include "Mock_Test2.h"
#include "Subdir1/Subdir2/Mock_Test3.h"
```

### Current Limitations:
- The FFF plugin's `setup_mocks()`-function still needs to be updated to allow sub-directory mocks **(BREAKING CHANGE)**
   Will do that if this is pull-requests is something thats needed/wanted.
- Mocking multiple headers with the same name is currently (probably) not supported because of the way ceedling handles dependencies.
- Unfortunatly a CMock update is required to allow it to generate mocks in Subdirectories.

### Further improvements:
 - Allowing ceedling to mock multiple headers with identical names could maybe achieved by modifying the way dependecy names are generated by [`file_path_utils.rb`](https://github.com/ThrowTheSwitch/Ceedling/blob/master/lib/ceedling/file_path_utils.rb#L116) and modifying the [`preprocessinator.rb`](https://github.com/ThrowTheSwitch/Ceedling/blob/master/lib/ceedling/preprocessinator.rb) to use it.
The [`file_finder.rb`](https://github.com/ThrowTheSwitch/Ceedling/blob/master/lib/ceedling/file_finder.rb) would probably also need to be updated aswell.

Disclaimer: Im no professional ruby developer so im more than happy for any feedback :)
If there are any issues please let me know :)

Related CMock pull request: https://github.com/ThrowTheSwitch/CMock/pull/327
Thanks to @alex116 for is work in #343.

### CODE REVIEW

**Comment by Hannes103** [comment]
Hello,

first of all: Thank you @mvandervoord for merging my PR in the CMock repository. I really appreciate it :) 

I resolved the merge conflicts by updating cmock submodule to the latest version and reversed it pointing to my custom version.

Is there anything else required in order for this to be mergeable? 
(Update the FFF plugin maybe? I will take a look if this pull request is something that is desired)

**Comment by mvandervoord** [comment]
@Hannes103 -- thanks for the good work! I think this is going to make a lot of people happy. Supporting subdirectories is a frequently-requested feature. 

I would definitely appreciate it if you resolved the FFF plugin issue. At that point, it appears it doesn't have any breaking changes and should be safe to submit. 

If you're interested in continuing to help, I'd love to see a followup PR towards handling the "same" filename under multiple directories. I'd be happy to help or talk through that.

**Comment by Hannes103** [comment]
@mvandervoord 
I have update the FFF plugin to also support sub folder mocks.
Once its merged this should also be ready.

However I would need some help to determine why the CI checks are failing. I cannot replicate it on my machine.
It seems to have some problems creating the `fake_project` folder. 
However it seems kind of random to me because I have not modified any tests.

**Comment by mvandervoord** [comment]
@Hannes103 -- It appears that Ceedling is crashing during most operations and not creating the projects it's supposed to be testing. Unfortunately, the errors being shown don't tell us much. I'll see if I can get it to send us more useful information.

**Comment by EighthMayer** [comment]
Hello!

I'm glad to inform you that [corresponding pull request to FFF plugin](https://github.com/ElectronVector/fake_function_framework/pull/27) is merged and included in the latest release ([v0.2.0](https://github.com/ElectronVector/fake_function_framework/releases/tag/v0.2.0)).

While I'm at it, @mvandervoord , may I ask you to please investigate why [FFF plugin distribution shipped with Ceedling gem is broken](https://github.com/ThrowTheSwitch/Ceedling/issues/245)? Considering presence of sublime text editor files in gem archive it looks like gem is generated manually, so I think this is some kind of human error leading to removal of plugin's "vendor" subfolder.

**Comment by papb** [comment]
Hello everyone! Happy to see this is a work in progress. This PR closes #358, right? Thanks!

**Comment by EighthMayer** [comment]
@papb hello! Yes, AFAIK this PR will solve the issue you linked.

**Comment by dylanlytle** [comment]
Is this going to be merged?

**Comment by Wojcik98** [comment]
Hello @Hannes103 @mvandervoord, are there any plans to merge this? This seems like really necessary feature.

I'm currently stuck at mocking inline functions that are included with subdirectories paths and this feature seems like the only way to do it.

**Comment by mvandervoord** [comment]
Thanks for the continued pings and especially for the original work! You people are great!

**Comment by Wojcik98** [comment]
Wow, that was fast! Thanks!

**Comment by mvandervoord** [comment]
Only if you ignore the date/time this thread actually started. ;)

**Comment by Wojcik98** [comment]
Yeah, it was more of a "that was fast reaction cosidering the activity in this PR" ;)

**Comment by EighthMayer** [comment]
@mvandervoord please please please [look into this issue](https://github.com/ThrowTheSwitch/Ceedling/issues/245) on the next release.

**Comment by RehabAbdAllah** [comment]
Hi is this merge in the latest release ?

**Comment by mvandervoord** [comment]
It is in the release candidate (which you can find by going to releases)

**Comment by RehabAbdAllah** [comment]
@mvandervoord Thanks .
Sorry for newbie question
can I install the Rc with  `gem install ceedling -v 0.32.0 ` ?

**Comment by mvandervoord** [comment]
Ruby gems don't get posted for the automatic installer until they are official releases... so if you'd like to test a release candidate, you download it to your machine, then from a command prompt in the same directory, you use this:

```
gem install --local ceedling-full-filename.gem
```

**Comment by Hannes103** [comment]
@mvandervoord Is there any work going on to allow ceedling to work with multiple files with identical names?
There seem to be a few issues mentioning this topic but im not entirely sure if this is something thats currently being worked on by someone?

If not, I might have a go at it.

Thanks in advance.

**Comment by mvandervoord** [comment]
A large portion of the work exists already and is in the pre-release branch for 0.32. This will likely be released without full support for this feature yet, but then it's a high priority to finish this feature for the next release. You're welcome to take a look at that branch. We appreciate the help!

**Pull request merged**
