### PR TITLE
Return total number of test failures as exit code

### PR DESCRIPTION
**Pull request by bvtthead**
Readdressing #174, and closing #538.

Don't really know too much about ruby, so very open to change requests.

### CODE REVIEW

**Comment by ntantisujjatham** [comment]
Should this also return a non-zero exit code upon any build failures happening?

**Comment by bvtthead** [comment]
Don't know too much about the flow of the program, just looked at it enough to get this bit done.
However, I think there is a check [here](https://github.com/ThrowTheSwitch/Ceedling/blob/d8c1fc5/lib/ceedling/rakefile.rb#L75) for any non-test non-zero exit codes.
Which makes leads me to believe that an `exit(1)` is required after [this](https://github.com/ThrowTheSwitch/Ceedling/blob/d8c1fc5/lib/ceedling/rakefile.rb#L83) line.

I think a configuration setting for how to handle exit codes would be useful.
And definitely, having an option for non-zero exit on build failure makes sense.

**Comment by dpostorivo** [comment]
This should definitely be a configuration option. 

Linux/Unix return codes only go from 0-255 so truncation could lead to odd results. Also things like the junit report plugin can currently give number of failed tests in a passable matter if that is the issue so there are ways to get failed test number outside of exit code.


As a side note, are #174 and #538 still known issues and if so can we get some exact detail? I've just tested it with the latest release and `ceedling test:all` and `rake test:all` both correctly return a non zero exit code on failure.

**Comment by ntantisujjatham** [comment]
@dpostorivo I was wondering what version of ceedling you are on? I am on 0.30.0

**Comment by bvtthead** [comment]
I get an exit code on build failure, but not test failure.
<details>
<summary><code>ceedling version</code></summary>

```
   Ceedling:: 0.31.1
      Unity:: 2.5.4
      CMock:: 2.5.4
 CException:: 1.3.3
```
</details>

<details>
<summary><code>ruby --version</code></summary>

```
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
```
</details>

**Comment by ntantisujjatham** [comment]
@bvtthead That's the same issue that I run into, which makes this tool difficult to put into a CI pipeline. I've been able to kind of get around this by wrapping the call to ceedling in a shell script that greps for "0 FAILED TESTS" on the last line. However, I've found that during certain type of build failures (namely related to including bad mocks), "0 FAILED TESTS" can still print out. I'd rather have a robust solution that deterministically reports out a non-zero error code whenever either:
1. a build failure happens
2. an unacceptable number of test failures happen

**Comment by bvtthead** [comment]
Example project: [bvtthead/ceedling-test](https://github.com/bvtthead/ceedling-test)

```
mkdir tests/build
ceedling; echo $?
```
yields
```
Test 'test_basic.c'
-------------------
Generating runner for test_basic.c...
Compiling test_basic_runner.c...
Compiling test_basic.c...
Compiling unity.c...
Compiling CException.c...
Compiling cmock.c...
Linking test_basic.out...
Running test_basic.out...
test_basic.c:3:test_basic_pass:PASS
test_basic.c:10:test_basic_fail:FAIL: Expected 6 Was 9

-----------------------
2 Tests 1 Failures 0 Ignored
FAIL
0
```
---
@ntantisujjatham I have to do the same thing for CI usage.

A non-zero exit code would work best with a CI pipeline.

And returning a fixed number instead of the number of tests seems reasonable to me, I was just restoring the previous functionality of `ceedling`. Currently I have no need to capture the number of test failures.

**Comment by dpostorivo** [comment]
@ntantisujjatham I'm on the last release 0.31.1

**Comment by dpostorivo** [comment]
@bvtthead  I see the failure now and it seems specifically to when the pretty reporting is disabled. 

I put this patch as a quick fix as a settings change. I'll check out this commit and see if this is the best path for it.

https://github.com/bvtthead/ceedling-test/pull/1

**Comment by mkarlesky** [comment]
I'm going to close this PR as much has changed for 0.32, and this PR was never reviewed and resolved (so sorry about that!).

Short version:

- Ceedling 0.32 should properly handle basic exit code scenarios now.
- A configuration option was added before 0.32 to toggle whether test failures trigger an exit code of 1 or 0 (defaults to exit code of 1 on test failures). Some have rightfully argued that test failures without build errors is still a successful exit (0). The simple toggle is especially important for different CI scenarios.
- Exiting with an exit code equal to the number of test failures is problematic — or at least quite challenging to handle. A single numeric exit code is too easily overloaded. Plugins and core Ceedling features can raise different build errors. Multiple sources can, in effect, stack build errors. How do we meaningfully distinguish one or more build errors from a test failure count? There might be a scheme where different aspects of the build could register different error contexts that then get processed in the finalization of a build with various options to produce the end user desired exit code. But, boy, this would be a lot of work. More importantly, we would almost certainly end up with logically inconsistent edge cases that we cannot adequately resolve.
- Ceedling 0.32's documentation now thoroughly discusses test failures vs. build errors as related to exit code handling along with the reasoning for the relatively simple scheme.

**Pull request closed without merging**
