### PR TITLE
Add @system_wrapper.module_eval to defineinator, flaginator, so enviroment variables, #{ENV['VARIABLE']}, are parsed now.

### PR DESCRIPTION
**Pull request by claudiiolima**

### CODE REVIEW

**Comment by claudiiolima** [comment]
This PR solves #879, so `flags` and `defines`, can be populate with enviroments variables now.

**Comment by mvandervoord** [comment]
Thanks for making your changes against the release candidate! That makes it much easier for us to consider this PR!

**Comment by mkarlesky** [comment]
Thank you so much for this. I am going to reject the PR but still implement the changes in a coming pre-release version. Like path standardization and related tasks, this should all be collocated in the startup steps that process configuration before it is used. The string replacement in tool handling is some of the very oldest code in Ceedling. It's not a pattern that should be copied elsewhere. We'll centralize this during configuration processing. This will have the added benefit of producing configuration modifications you can see and verify by running the new `dumpconfig` command line.

**Comment by claudiiolima** [comment]
Only to track modifications [✨ Ruby string replacement for :defines & :flags](https://github.com/ThrowTheSwitch/Ceedling/commit/7ce8c3b894545364b81d9a0ae2fa9849c67a5d01)

**Pull request closed without merging**
