### PR TITLE
Allow ability to specify keys for imports

### PR DESCRIPTION
**Pull request by germouse12**
Instead of using an array of imports, you can use hashes so that certain imports can be replaced by option files.

Not sure what other use cases there might be for this, but in my case, I was having to use 2 separate .ymls for two different types of test runs: host and simulator. I would have preferred that it defaults to the host without any "option:" or "project:" command line arguments. Unfortunately, there are certain things that need to be removed from the host configuration, to make the simulator configuration run correctly. This isn't possible when the host configuration uses the overall project.yml.

My solution to the problem was to change the :import: section of the project.yml to hashes so that the base configuration imports can be replaced by name in the option/project specific .ymls. This was in lieu of recoding the yaml_merger to allow replacement instead of addition. For backwards compatibility, I kept the old method of iterating the array and just ran a test to see if :import: was an array or not.

I will caveat all of my changes with I am not very familiar with Ruby at all. I can almost guarantee there is a better/more efficient/more robust/safer way to do this, it was just my initial hack at it. I would also understand if this isn't desirable behavior for most people and won't be implemented.

### CODE REVIEW

**Comment by mvandervoord** [comment]
I like this idea a lot. Thanks for submitting this. Do you mind also adding a note in the documentation about how it can work?

**Comment by germouse12** [comment]
I can do that, yeah. Couple questions first though:

1. Should I keep it as it is to preserve the ability to use an array instead of hashes? Or replace arrays entirely (thereby breaking implementations for anyone using this currently)?

2. I realized I don't really know how option files (i.e. the options: command line argument) work. I tested this with project: and it worked, but I can't get the options: way to work. Is there a difference in the two and would my commit be compatible with those differences?

3. I think my initial problem would better be solved by having the project: command replace the default project.yml entirely rather than merging with that file. Would this be an acceptable alternative? Basically, the main project.yml would hold the default options (with likely several imports for common options) and using project: would replace that file likely with a different mixture of imports. This is really what I wanted to do, but my current fix was quicker/easier. Not sure I would have the expertise to implement that change without significant investment (actually learning Ruby...).

Overall, I am a bit confused about the differences between options:, project:, and :import:. They seem to be doing similar things, but in different ways and with different externalities.

One other issue for this commit is that I don't know of a way to remove the import. In my example, the project.yml imports host.yml with the hash ":method:". When I use project:simulator, I no longer need any import referenced by ":method:" but providing nothing or an empty string threw errors. I ended up just using simulator.yml which is not very pretty and I am not sure what other nasty things may pop up from a .yml importing itself...

Any thoughts/opinions/inputs are appreciated. No rush either. This is more of a hobby for me, so no deadlines to speak of.

**Comment by mvandervoord** [comment]
1. Definitely don't break backwards compatibility. I think you've done a good job by supporting both methods here.

2. I suspect that maybe with the options file, your issue might have been not specifying where to find the options files (setting the path for it) or not having the options files in that path? It's very choosy about the naming. Otherwise I think this should be compatible.

3. The difference between project: and options: is that the latter only replaces defines and a few other minor things... where project: will overwrite anything that you specify in the second project file. I'm not sure of a situation where that doesn't work... if you've run into problems with that, I'd like to hear about it. We *may* be collapsing this all down to a single feature anyway, to solve the exact problem you're running into: It's not clear what does what.

As for :import... I never really use it... so I'd have to dig into it and refresh my memory of how it even works. :)

**Comment by germouse12** [comment]
1. 👍 
2. It was finding it no problem, but it was throwing an error about not finding the compiled runner file. I'm going to chalk it up to it only replacing, as you say "defines and a few other minor things." There was a lot more in that options file and it just appeared to break everything.
3. It seems that import uses the same deep_merge! method as the options: command, but there's probably a lot more that goes into it that it causing one to break and not the other.

Doc edits coming, hopefully today. Have some "actual" work to do first. Thanks for the inputs and clarifications! I really have enjoyed delving into this project and the work you've put into it!

**Comment by germouse12** [comment]
@mvandervoord Take a look and see if this is clear enough. Also, I made it possible to get rid of the specified import by not setting the value; it helps with the one issue I was having.

**Pull request merged**
