### PR TITLE
project:xxx is not a rake task -> is filtered from the ARGV array to …

### PR DESCRIPTION
**Pull request by grosi**
…prevent unknown task calls

### CODE REVIEW

**Comment by mvandervoord** [comment]
Can you provide an example of a failure that you've run into regarding this? I've not seen the problem you are citing.

**Comment by grosi** [comment]
Use case as followed: A project with multiple project-YAML files (e.g. project.yml -> for testing; xxx.yml -> for release configuration 1; yyy.yml -> for release configuration 2.
As you mentioned in this post (http://www.throwtheswitch.org/forums?place=msg%2Fthrowtheswitch%2FYDYiaH6yCb0%2FAH2d0VFwAwAJ) , I use ‘ceedling project:yyy release’ to build the release configuration 2. With version 0.27.0 this works as expected. With version 0.28.1 however, ceedling returns an error (‘Don’t know how to build task ‘project:yyy’’).

**Comment by mvandervoord** [comment]
When you upgraded to 0.28.1, did you just upgrade your gem or did you actually run "ceedling upgrade" on your project? Does it behave the same if you remove (or rename) your rakefile to something else?

Our online tests for this feature are passing and I just created a few modules with 0.28.1 myself and it went fine. I'm just trying to hunt down what might be different with your setup so I know where the bug is. :)

**Comment by grosi** [comment]
I did upgrade my gem and reinit the project with "ceedling new PROJECT_NAME". With version 0.28.1, I removed the rakefile (seems to be obsolet?).

Today I tested it again. First with version 0.27.0 -> project:yyy works, but the error "NameError: uninitialized constant ReleaseInvoker:: EXTENSION_SUBPROJECT" appears.
With version 0.28.1 I get the same as I mentioned in post #199 . Before I tested each version, I removed the old one (gem uninstall ceedling --version xx.xx.xx)

Or maybe I miss a project option? Currently my project.yml file looks like follow:
```
:project:
  :build_root: build
  :graceful_fail: true
  :test_file_prefix: test_
  :use_deep_dependencies: true
  :use_exceptions: false
  :use_test_preprocessor: true
  :default_tasks: test:all

:environment:
- :path:
  - '#{ENV[''ATOLLIC_PC_HOME'']}'
  - '#{ENV[''ATOLLIC_ARM_HOME'']}'
  
:defines:
  :common: &id001
  - STM32L486xx
  
  :test:
  - *id001
  - TEST
  
  :test_preprocess:
  - *id001
  - TEST
  
:paths:
  :source:
  - src/**
  :support:
  - test/support/**
  :test:
  - +:test/**
  - -:test/support/**
  :test_toolchain_include:
  - '#{ENV[''ATOLLIC_PC_INCLUDE'']}'
  - '#{ENV[''ATOLLIC_PC_LIB_INCLUDE'']}'
  - '#{ENV[''ATOLLIC_PC_LIB_INCLUDE_FIXED'']}'
  - '#{ENV[''ATOLLIC_PC_MINGW_INCLUDE'']}'

:extension:
  :assembly: .s
  :executable: .out
  :header: .h
  :object: .o
  :source: .c
 
:tools:
  :test_compiler:
    :executable: gcc
    :arguments:
    - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
    - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
    - -std=gnu11
    - -c
    - -fmessage-length=0
    - -g
    - -O2
    - ${1}
    - -o "${2}"
    
  :test_linker:
    :executable: gcc
    :arguments:
    - ${1}
    - -o ${2}
    
  :test_assembler:
    :executable: ar
       
:cmock:
  :enforce_strict_ordering: true
  :mock_prefix: mock_
  :plugins:
  - :ignore
  - :ignore_arg
  - :callback
  :treat_as:
    bool: UINT8
    int8: INT8
    uint16: HEX16
    uint32: UINT32
    uint8: HEX8
  :treat_externs: :include
  :when_no_prototypes: :warn
  :when_ptr: :smart
    
:plugins:
  :enabled:
  - stdout_pretty_tests_report
  - module_generator
  - warnings_report
  - xml_tests_report
  :load_paths:
  - vendor/ceedling/plugins
```

**Comment by mvandervoord** [comment]
My apologies, @grosi . It was I who wasn't refreshing my local changes well enough. The bug you found is much more consistent than I was seeing. Thanks for sticking with it and thanks for the help!

**Comment by grosi** [comment]
No problem! Thank you for developing and sharing Ceedling! It makes my life much easier :-)

**Pull request merged**
