### PR TITLE
Improve Gcov reports

### PR DESCRIPTION
**Pull request by dpostorivo**
This commits does some work on the gcov plugin most of which is clean up.
The two new things this commit does:

- Now puts the gcov coverage html report into artifacts  
- Adjust level of detail in the report by defining either 'basic' or 'advanced'

The new setting can be added to the project.yml as such:

```
:gcov:
  :html_report_type: basic
```

or

```
:gcov:
  :html_report_type: advanced
```

### CODE REVIEW

**Comment by Letme** [comment]
Did you notice that it does not take gcov_compiler, etc. from the target file but rather from the provided default.yml file (inside plugin?) Can we maybe fix that as well?

**Comment by dpostorivo** [comment]
@Letme  yes, but it's not an easy conversion as then we will need to get all settings from the configuratior and default back to the hardcoded if the configurator's settings are not found. After this update I actually understand the configuratior will enough to do it. 


I'd also need to look into how compatible the gcov's results display would be with different configurations as I'm not sure how tightly coupled they are with the hardcoded options.

**Comment by Letme** [comment]
I have simply deleted default options and now it seems to work just fine. There is some difference with how current `test_compiler` config handles object and source files (not needed to be `-o {2} -c {1}` flags anymore), I would assume `gcov_compiler` would do the same and after deleting settings I needed to find correct parameters myself with a bit of playing but now it works if I compile with `gcc` or with `clang` (`gcov` or `llvm-cov` - and some wrapper script to make it `llvm-cov gcov`).

I would be very happy if you could do it - I am willing to send you some chocolate :smiley:

**Comment by dpostorivo** [comment]
I'll see what I can do over the next few days. No promises, but I'll at least try.

**Comment by mvandervoord** [comment]
I don't know the gcov plugin itself well, but I've recently built and/or cleaned up some of the other plugins. If I can answer a question or two, feel free to email me directly.

**Comment by dpostorivo** [comment]
@Letme 

After some experimenting, it seems this functionality already exists in the same fashion as it does in the normal Ceedling. I was able to get llvm-cov by doing the following:


```
:tools:
  :gcov_compiler:
    :executable: clang
    :arguments:
      - -fprofile-arcs
      - -ftest-coverage
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -c "${1}"
      - -o "${2}"
  :gcov_linker:
    :executable: clang
    :arguments:
      - --coverage
      - ${1}
      - -o ${2}
  :gcov_fixture:
    :executable: ${1}
  :gcov_report:
    :executable: llvm-cov-3.5
    :arguments:
      - -n
      - -p
      - -b
      - -o "$": GCOV_BUILD_OUTPUT_PATH
      - "\"${1}\""

```

I will admit these settings we're not 100% and I kept getting odd errors from llvm-cov (unexpected number of edges), but at least it ran in a way that someone who does work with llvm-cov could probably get running easily.

**Comment by Letme** [comment]
@dpostorivo I can paste you my ones which also works, but you need to delete `default.yml`

Thing is, new Ceedling conf does not need `${1}` in compiler and linker, it also does not need `-I`s since it takes that from `:flags:` directive (which remembers me I have `:test:` in flags but not `:gcov:`, so that might be a reason).

Anyway I have following
```
 :gcov_compiler:
    :executable: clang
    :arguments:
      - -Iemlib/inc/
      - -IEFM32TG/Include/
      - -ICMSIS/Include/
      - -D'__ARM__'
      - -D'__SOFTFP__'
      - -D'__CLANG__'
      - -Wno-pointer-to-int-cast
      - -Wno-int-to-pointer-cast
      - -Wall
      - -Wno-address
      - -Wno-attributes
      - -Wno-unused-function
      - -std=c99
      - -fshort-enums
      - -pedantic
      - -fprofile-arcs
      - -ftest-coverage
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -c ${1}                       #source code input file (Ruby method call param list sub)
      - -o ${2}                       #object file output (Ruby method call param list sub)
  :gcov_linker:
    :executable: clang
    :arguments:
      - ${1}
      - -lm
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -lgcov
      - --coverage
      - -o ${2}            #executable file output (Ruby method call param list sub)
  :gcov_fixture:
    :executable: ${1}
  :gcov_report:
    :executable: llvm-cov
    :arguments:
      - gcov
      - -n
      - -p
      - -b
      - -o "$": GCOV_BUILD_OUTPUT_PATH
      - "\"${1}\""
  :gcov_post_report:
    :executable: lcov
    :optional: FALSE
    :arguments:
        - --directory build/gcov/out/
        - --gcov-tool './scripts/llvm-gcov.sh'
        - --no-external
        - --capture
        - --config-file .lcovrc
        - --output-file build/artifacts/gcov/lcov.info
```
and scripts/llvm-gcov.sh is just a wrapper for llvm-cov with gcov as direct argument.
```
#!/bin/bash
exec llvm-cov gcov "$@"
```

However to get a proper nice report out, I still need to have a target in `Makefile` for genhtml:
```
	@$(GENHTML) build/artifacts/gcov/lcov.info -o build/coverage/ --config-file .lcovrc
```

**Comment by dpostorivo** [comment]
@Letme  I'm not sure why you would have to delete `default.yml`. Is it just the `gcov_post_report` that doesn't work if default or is it all of the gcov plugin?

**Comment by Letme** [comment]
It seems like I have some really specific stuff, but if `default.yml` is there, it does not use the clang to compile, but normal GCC and then concats arguments together, while  executable remains the on in default. Of course if I change the one in `default.yml` then it uses that program. 

Fishy thing is also that dependencies and preprocessing is also done by gcc, but I assume this is because I do not have nothing for that defined in my clang target yml (only compiler&linker, test_compiler&test_linker, gcov_compiler&gcov_linker&gcov_fixture&gcov_report) .

**Comment by mvandervoord** [comment]
@Letme I *think* that issue has been taken care of? There were some quirks in the way configuration options were getting merged that I believe are doing better now?

**Comment by Letme** [comment]
This is all fairly **unrelated** to this MR which can go in as it is.

On the other side, I have applied the patch to latest master, but I get order of flags mixed. I do not know what might be wrong, but

```targets/clang.yml
  :gcov_report:
    :executable: llvm-cov
    :arguments:
      - gcov
      - -n
      - -p
      - -b
      - -o "$": GCOV_BUILD_OUTPUT_PATH
      - "\"${1}\""
```
Produces error:
```
> Shell executed command:
'llvm-cov -n -p -b -o "build/gcov/out" "adc.c" gcov'
> And exited with status: [1].
```
Order of flags passed changed for some reason (and here it is important). It was preserved before this I also tried 'llvm-cov gcov' as executable, but then it complains (as before)
```
ERROR: Config filepath [:tools][:gcov_report][:executable]['llvm-cov gcov'] does not exist in system search paths.
```

Anyway unrelated and should not be blocking this MR.

**Comment by Letme** [comment]
OK edit of above: This PR does not introduce anything new. The issue from above is fixed if I delete `default.yml` in gcov plugin . This should be merged in.

**Pull request merged**
