### PR TITLE
Add two configuration tokens to configure output file name for junit_tests_report and xml_tests_report plugins.

### PR DESCRIPTION
**Pull request by achsfy**
#323
If configuration tokens are not used, behavior isn't modified.
Otherwise, this makes it possible to change the output file of junit_tests_report or/and xml_tests_report plugins.

### CODE REVIEW

**Comment by danebou** [comment]
@achsfy CI build failed?

**Comment by achsfy** [comment]
> 
> 
> @achsfy CI build failed?

Yes, I'm waiting for #328 to be accepted.

**Comment by aschlicht** [comment]
I made a similar change to junit_tests_report, came here to contribute, and see @achsfy already made the changes. I'd like to see these changes merged so I can deprecate a build server Python script that we have as workaround. Can I help in any way?

I see @achsfy's changes require project.yml to be modified under the `:plugins:` section, as shown below. Other plugins, like gcov, do not require the config options to be under `:plugins:`. Not sure which way is "correct". I like consistency.

```
:plugins:
  :junit_tests_report:
    :out_file_name: report_junit.xml
```

**Comment by achsfy** [comment]
> 
> 
> I made a similar change to junit_tests_report, came here to contribute, and see @achsfy already made the changes. I'd like to see these changes merged so I can deprecate a build server Python script that we have as workaround. Can I help in any way?
> 
> I see @achsfy's changes require project.yml to be modified under the `:plugins:` section, as shown below. Other plugins, like gcov, do not require the config options to be under `:plugins:`. Not sure which way is "correct". I like consistency.
> 
> ```
> :plugins:
>   :junit_tests_report:
>     :out_file_name: report_junit.xml
> ```

You are right about this.
So should I create a section for each plugin?

I also see that gcov is calling output files _artifacts_. To keep vocabulary close to what is usual in CI, should I use _artifact_?

This would look like the following:
```
:junit_tests_report:
  :artifact: report_junit.xml

:xml_tests_report:
  :artifact: report_xml.xml
```

**Comment by mvandervoord** [comment]
I believe that elsewhere in ceedling they are referred to as artifacts... so if you're going to change it, it would have to be done everywhere.

**Comment by aschlicht** [comment]
@achsfy Yes, please use a separate section for each plugin. The plugins don't rely on each other, so let's keep them decoupled. Looks like all you need to do is remove the text "plugins_" from each change and commit again. Do you have time to make the change?

@mvandervoord What name do you prefer for the configuration options to specify the filename? You're the guy in charge, so your opinion is welcome. Looking into the future, someone might want to specify an output path, so maybe we want to include "filename" to differentiate?

Some options...
:artifact:
:artifact_filename:
:artifact_file_name:
:out_filename:
:out_file_name:
:output_filename:
:output_file_name:

**Comment by mvandervoord** [comment]
I like `artifact_filename` or `output_filename` personally. No strong preference between the two. :)

**Comment by aschlicht** [comment]
@achsfy I tested your updates and I was wrong about simply removing "plugins_". At least it doesn't work for me. The following two ways work from my testing.

```Ruby
artifact_filename = @ceedling[:configurator].project_config_hash[:xml_tests_report_artifact_filename]
artifact_filename = @ceedling[:configurator].project_config_hash.dig(:xml_tests_report_artifact_filename)
```

@mvandervoord The change uses the .dig() function, which I don't see anywhere else in the ceedling repository. A brief Internet search says .dig() was added in Ruby 2.3 while https://www.throwtheswitch.org/ceedling says one needs to install Ruby 1.8.6 or newer. Is that Ruby version requirement still valid? Do you want to include a Ruby 2.3 or later feature? There is an old gem called ruby_dig to support dig() in older versions of Ruby https://rubygems.org/gems/ruby_dig/versions/0.0.2.

**Comment by achsfy** [comment]
@aschlicht I took the version without dig, this shall fix the issue related to Ruby version isn't it?

**Comment by aschlicht** [comment]
@achsfy Yes, removing the use of .dig() fixes the potential issue with requiring a newer version of Ruby. Thank you for making the changes. I ran your latest code with and without the configuration options defined. It's all looking good.  

How do we let other people know about these new configuration options? I like README.md files. I attached one for each plugin, if you like the approach. github wont let me upload .md files, so I renamed the extension to .txt. If you like these, please copy to the corresponding directories and rename to README.md. Do you have another idea?

[README_xml_tests_report.txt](https://github.com/ThrowTheSwitch/Ceedling/files/3128772/README_xml_tests_report.txt)
[README_junit_tests_report.txt](https://github.com/ThrowTheSwitch/Ceedling/files/3128775/README_junit_tests_report.txt)

**Comment by achsfy** [comment]
@aschlicht README are ok for me. 
I've added you as a collaborator to achsfy/Ceedling repo so you shall be able to contribute to this PR.

**Comment by aschlicht** [comment]
@achsfy Thank you for adding me as a collaborator. I pushed the two README.md files to master and made no other code changes. Hopefully you are ok with me pushing to master and not another branch. I think your code is good to go and could be merged into the mainline. Could you please review the README files and either make the changes yourself or comment on changes you'd like to see? Thank you!

In a typical development process, we create a branch, work on the branch, and then before submitting a pull / merge request, we merge master into our branch to resolve any issues on the branch. Then the merge back into master is clean and shows only the changes made on the branch. Shall we merge the latest Ceedling mainline into your fork before completing the pull request?

**Comment by mvandervoord** [comment]
I'd appreciate it if you all would let me know when you are feeling happy with this pull and want it to grab it. :)

**Comment by aschlicht** [comment]
@mvandervoord I'm happy with achsfy's code changes. Would you like to review the README.md files I made? Is there anything you'd like me to add / remove / modify in the README files? (Any typos?) Thanks!

**Comment by danebou** [comment]
Really excited this is about to be merged. Can finally have CI results and VS code test UI without having to mod the config file!

**Comment by mvandervoord** [comment]
@aschlicht -- looks good to me.

**Comment by aschlicht** [comment]
@danebou You're welcome! Is there another similar feature you'd like to see or are we missing anything with these changes? Do the readme files provide enough help? Thanks!

**Comment by aschlicht** [comment]
Thanks for the review, Mark. I'm ready for the pull request to be completed.

**Comment by achsfy** [comment]
Looks all good to me!

**Comment by OlegSomov** [comment]
It seems as a great feature. I'm currently experiencing issue, when the `:artifact_filename:` doesn't really work.

```
  Ceedling:: 0.28.3
CException:: 1.3.1.18
     CMock:: 2.4.6.217
     Unity:: 2.4.3.122
```
`project.yml` part with plugins configuration
```
:junit_tests_report:
  :artifact_filename: report_junit.xml

:xml_tests_report:
  :artifact_filename: report_xunit.xml
:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - xml_tests_report
    - junit_tests_report
    - stdout_pretty_tests_report
    - module_generator
    - raw_output_report
    - gcov
```
I run `ceedling` and `ceedling gcov:all utils:gcov` and get files are still named `report.xml`

Another interesting "bug", i guess, that if I have xml and JUnit enabled the VSCode plugin doesn't work. It just get's stuck on running stage. Command line works (well, except the names)
image

**Comment by aschlicht** [comment]
@OlegSomov I'm glad you like the feature. While this change is merged into master, there hasn't been a [ceedling release](https://github.com/ThrowTheSwitch/Ceedling/releases) since Aug 8, 2018. 

@mvandervoord When do you plan on making the next ceedling release? Do you need some help? I'd like to see all the latest changes be available in the gem. If you're feeling more ambitious, there are two more pull requests within the last six months that could be tested, merged, and released as well.

**Comment by psheph** [comment]
@OlegSomov 
In the short-term, you may be able to modify the internal files as I describe in [this blog post](https://embeddedartistry.com/blog/2019/2/25/unit-testing-and-reporting-on-a-build-server-using-ceedling-and-unity?utm_sq=g0nuhwzfkk&utm_source=LinkedIn&utm_medium=social&utm_campaign=PhillipJohnston&utm_content=OwnBlogPosts). It's definitely a hack, and I am looking forward to 0.28.4 to make it all official!

> It seems as a great feature. I'm currently experiencing issue, when the `:artifact_filename:` doesn't really work.
> 
> ```
>   Ceedling:: 0.28.3
> CException:: 1.3.1.18
>      CMock:: 2.4.6.217
>      Unity:: 2.4.3.122
> ```
> 
> `project.yml` part with plugins configuration
> 
> ```
> :junit_tests_report:
>   :artifact_filename: report_junit.xml
> 
> :xml_tests_report:
>   :artifact_filename: report_xunit.xml
> :plugins:
>   :load_paths:
>     - vendor/ceedling/plugins
>   :enabled:
>     - xml_tests_report
>     - junit_tests_report
>     - stdout_pretty_tests_report
>     - module_generator
>     - raw_output_report
>     - gcov
> ```
> 
> I run `ceedling` and `ceedling gcov:all utils:gcov` and get files are still named `report.xml`
> 
> Another interesting "bug", i guess, that if I have xml and JUnit enabled the VSCode plugin doesn't work. It just get's stuck on running stage. Command line works (well, except the names)
> image

**Pull request merged**
